name: dotnet

on:
  pull_request:

permissions: {}

jobs:
  compute:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Free additional disk space
      run: |
          sudo apt purge -yq $(dpkg -l | grep '^ii' | awk '{ print $2 }' | grep -P '(aspnetcore|cabal-|dotnet-|ghc-|libmono|mongodb-|mysql-|php)') \
            firefox google-chrome-stable microsoft-edge-stable mono-devel mono-runtime-common monodoc-manual ruby
          sudo apt autoremove -yq
          sudo apt clean
          sudo rm -fr /opt/ghc /opt/hostedtoolcache /usr/lib/node_modules /usr/local/share/boost /usr/share/dotnet /usr/share/swift
    - name: Clone dotnet repo
      run: |
        pwd
        git clone https://github.com/dotnet/dotnet --depth 1
    - name: Prep
      run: |
        pwd
        cd dotnet
        ./prep-source-build.sh
        git status
    - name: Build
      run: |
        pwd
        cd dotnet
        ./build.sh
        git status
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-${{ github.sha }}
        path: ./dotnet
